name: Email Sentiment Analysis

on:
  schedule:
    # Run every hour 
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze-sentiment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run email sentiment analysis
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python app.py