name: Email Sentiment Analysis

on:
  schedule:
    # Run every hour 
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze-sentiment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t email-sentiment-analyzer .
      
    - name: Run Docker container
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        docker run --rm \
          -e EMAIL_ADDRESS="${EMAIL_ADDRESS}" \
          -e EMAIL_PASSWORD="${EMAIL_PASSWORD}" \
          email-sentiment-analyzer